version: '3.8'

services:
  # MongoDB servisi
  mongodb:
    image: mongo:6.0
    container_name: yazmuh-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: yazmuh-proje
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - yazmuh-network

  # Redis servisi
  redis:
    image: redis:7-alpine
    container_name: yazmuh-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - yazmuh-network

  # RabbitMQ servisi
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: yazmuh-rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password123
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - yazmuh-network

  # Backend uygulaması
  backend:
    build: .
    container_name: yazmuh-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGO_URI: mongodb://admin:password123@mongodb:27017/yazmuh-proje?authSource=admin
      REDIS_URL: redis://redis:6379
      RABBITMQ_URL: amqp://admin:password123@rabbitmq:5672
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
      ENABLE_RABBITMQ: "true"
      EMAIL_HOST: smtp.gmail.com
      EMAIL_PORT: 587
      EMAIL_USER: your-email@gmail.com
      EMAIL_PASS: your-app-password
      FRONTEND_URL: http://localhost:3000
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - mongodb
      - redis
      - rabbitmq
    networks:
      - yazmuh-network

  # E-posta worker
  email-worker:
    build: .
    container_name: yazmuh-email-worker
    restart: unless-stopped
    environment:
      NODE_ENV: production
      MONGO_URI: mongodb://admin:password123@mongodb:27017/yazmuh-proje?authSource=admin
      REDIS_URL: redis://redis:6379
      RABBITMQ_URL: amqp://admin:password123@rabbitmq:5672
      EMAIL_HOST: smtp.gmail.com
      EMAIL_PORT: 587
      EMAIL_USER: your-email@gmail.com
      EMAIL_PASS: your-app-password
      FRONTEND_URL: http://localhost:3000
    command: ["node", "workers/emailWorker.js"]
    depends_on:
      - mongodb
      - redis
      - rabbitmq
    networks:
      - yazmuh-network

volumes:
  mongodb_data:
  redis_data:
  rabbitmq_data:

networks:
  yazmuh-network:
    driver: bridge 